// <auto-generated />
using System;
using FonTakip.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FonTakip.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720074933_AddPortfolioTable")]
    partial class AddPortfolioTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FonTakip.API.Models.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            Code = "MAC",
                            IsActive = true,
                            Name = "Marmara Capital Hisse Senedi Fonu"
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            Code = "AFT",
                            IsActive = true,
                            Name = "Ak Portföy Teknoloji Şirketleri Fonu"
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            Code = "YAF",
                            IsActive = true,
                            Name = "Yapı Kredi Altın Fonu"
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            Code = "NNF",
                            IsActive = true,
                            Name = "Hedef Portföy Birinci Hisse Senedi Fonu"
                        });
                });

            modelBuilder.Entity("FonTakip.API.Models.FundPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FundId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("FundPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangeRate = 0m,
                            Date = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 1,
                            Price = 13.00m
                        },
                        new
                        {
                            Id = 2,
                            ChangeRate = 1.5m,
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 1,
                            Price = 13.20m
                        },
                        new
                        {
                            Id = 3,
                            ChangeRate = 2.2m,
                            Date = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 1,
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 4,
                            ChangeRate = 1.1m,
                            Date = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 1,
                            Price = 13.65m
                        },
                        new
                        {
                            Id = 5,
                            ChangeRate = 6.3m,
                            Date = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 1,
                            Price = 14.52m
                        },
                        new
                        {
                            Id = 6,
                            ChangeRate = 0m,
                            Date = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 2,
                            Price = 26.10m
                        },
                        new
                        {
                            Id = 7,
                            ChangeRate = 2.6m,
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 2,
                            Price = 26.80m
                        },
                        new
                        {
                            Id = 8,
                            ChangeRate = 2.6m,
                            Date = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 2,
                            Price = 27.50m
                        },
                        new
                        {
                            Id = 9,
                            ChangeRate = 1.8m,
                            Date = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 2,
                            Price = 28.00m
                        },
                        new
                        {
                            Id = 10,
                            ChangeRate = 1.0m,
                            Date = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FundId = 2,
                            Price = 28.30m
                        });
                });

            modelBuilder.Entity("FonTakip.API.Models.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FundId")
                        .HasColumnType("int");

                    b.Property<decimal>("Shares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("FonTakip.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FonTakip.API.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FundId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("FonTakip.API.Models.FundPrice", b =>
                {
                    b.HasOne("FonTakip.API.Models.Fund", "Fund")
                        .WithMany("Prices")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FonTakip.API.Models.PortfolioItem", b =>
                {
                    b.HasOne("FonTakip.API.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FonTakip.API.Models.UserFavorite", b =>
                {
                    b.HasOne("FonTakip.API.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FonTakip.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FonTakip.API.Models.Fund", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
